name: Bookmarklet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Bookmarklet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Run Python
        run: python code_exporter.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bookmarklet
          path: export/YT-Membership-exporter.js