name: Bookmarklet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Bookmarklet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: export Bookmarklet
        run: python code_exporter.py
      - name: export exe
        run: pyinstaller --onefile YT-Membership-exporter.server.py

      - name: move exe
        run: mv dist/server.exe /export/YT-Membership-exporter.server.exe


      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: YT-Membership-exporter
          path: export/
