name: Bookmarklet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  MakeLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Export Bookmarklet
        run: python code_exporter.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Bookmarklet.zip
          path: export/

